apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
data:
  DB_HOST: "mysql" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: mahadevan045/backend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits: #limits is greater than or equal to requests
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backend # name of the config-map
---
apiVersion: v1
kind: Service 
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 #service port 
    targetPort: 8080 # container port
